# Generated by Django 4.0.3 on 2022-04-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin_app', '0003_remove_accountgroup_account'),
        ('user_management_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
