# Generated by Django 4.0.4 on 2022-04-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin_app', '0003_remove_accountgroup_account'),
        ('user_management_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
