# Generated by Django 4.0.4 on 2022-05-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0002_remove_message_user_remove_message_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
