# Generated by Django 4.0.3 on 2022-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0003_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmodel',
            name='has_unread',
            field=models.BooleanField(default=False),
        ),
    ]
