# Generated by Django 4.0.4 on 2022-04-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management_app.account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='account',
            field=models.ManyToManyField(through='web_admin_app.PersonGroup', to='user_management_app.account'),
        ),
    ]
