# Generated by Django 4.0.3 on 2022-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0001_initial'),
        ('web_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonGroup',
            new_name='AccountGroup',
        ),
        migrations.RemoveField(
            model_name='group',
            name='account',
        ),
    ]
