# Generated by Django 4.0.4 on 2022-04-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin_app', '0002_rename_persongroup_accountgroup_remove_group_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroup',
            name='account',
        ),
    ]
