# Generated by Django 4.0.4 on 2022-04-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin_app', '0003_remove_accountgroup_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountGroup',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
