# Generated by Django 4.0.4 on 2022-05-15 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows'), ('Other', 'Other')], default=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows'), ('Other', 'Other')], max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('keywords', models.CharField(max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit'), ('Other', 'Other')], default=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit'), ('Other', 'Other')], max_length=2000)),
                ('image', models.BinaryField(blank=True, editable=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated', to='product_listing_app.post')),
                ('rater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='product_listing_app.post')),
            ],
        ),
    ]
