# Generated by Django 4.0.4 on 2022-05-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows')], default=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows')], max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('keywords', models.CharField(max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit')], default=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit')], max_length=2000)),
                ('image', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Image')),
                ('date', models.DateField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
            ],
        ),
    ]
