# Generated by Django 4.0.3 on 2022-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(default='Books', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(default='status', max_length=2000),
        ),
    ]
