# Generated by Django 4.0.3 on 2022-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0002_post_post_category_post_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies')], default='Books', max_length=2000),
        ),
    ]
