# Generated by Django 4.0.3 on 2022-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0003_alter_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows')], default='Books', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG')], default='PG13', max_length=2000),
        ),
    ]
