# Generated by Django 4.0.3 on 2022-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0004_alter_post_post_category_alter_post_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit')], default='PG13', max_length=2000),
        ),
    ]
