# Generated by Django 4.0.3 on 2022-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0005_alter_post_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
