# Generated by Django 4.0.4 on 2022-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0008_post_post_image_post_post_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows')], default=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit')], default=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit')], max_length=2000),
        ),
    ]
