# Generated by Django 4.0.4 on 2022-05-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0009_alter_post_post_category_alter_post_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_keywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
    ]
