# Generated by Django 4.0.4 on 2022-05-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0010_rename_post_category_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
