# Generated by Django 4.0.4 on 2022-05-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0012_posts_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
