# Generated by Django 4.0.4 on 2022-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0013_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
