# Generated by Django 4.0.4 on 2022-05-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0014_post_author_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
