# Generated by Django 4.0.4 on 2022-05-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0015_rename_author_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
