# Generated by Django 4.0.4 on 2022-05-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0014_post_flagged'),
        ('product_listing_app', '0016_rename_user_post_author'),
    ]

    operations = [
    ]
