# Generated by Django 4.0.4 on 2022-05-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0024_alter_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows'), ('Other', 'Other')], default=[('Books', 'Books'), ('CDs', 'CDs'), ('Videos', 'Videos'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows'), ('Other', 'Other')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit'), ('Other', 'Other')], default=[('PG13', 'PG13'), ('R', 'R'), ('PG', 'PG'), ('Explicit', 'Explicit'), ('Other', 'Other')], max_length=2000),
        ),
    ]
