# Generated by Django 4.0.4 on 2022-05-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0027_rename_rated_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='posting',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='rater',
        ),
    ]
