# Generated by Django 4.0.4 on 2022-05-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0029_alter_rating_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='posting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
