# Generated by Django 4.0.4 on 2022-05-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0030_alter_rating_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='product_listing_app.post'),
        ),
    ]
