# Generated by Django 4.0.4 on 2022-05-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0031_alter_rating_posting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='rating',
            name='posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated', to='product_listing_app.post'),
        ),
    ]
