# Generated by Django 4.0.4 on 2022-05-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0017_merge_0014_post_flagged_0016_rename_user_post_author'),
        ('product_listing_app', '0032_rename_rating_rating_rate_alter_rating_posting'),
    ]

    operations = [
    ]
