# Generated by Django 4.0.4 on 2022-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing_app', '0037_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
